[Sui]
    Chain = "Sui"
    Enabled = true
    NetworkAddress = "https://fullnode.testnet.sui.io:443" # a network address
    PackageId = "0x13d6408c07b9924cf8e57efc5ffc340314dbfa361c870821c65ae5549745e98e"
    BridgeObjectId = "0x9df542a1873d2c154cd2c19bcfaed78ea39f5054e9f0e09b424c151321021436"
    BridgeObjectInitialSharedVersion = 586569728
    SafeObjectId = "0x176831b799d0edbf37515c189bab34fe2822bc1188a88aae791fa303c6e4fb41"
    SafeObjectInitialSharedVersion = 586569727
    TreasuryObjectId = "0xd9104c0dba662a57ba25ea88dc4dc9c15068547a06791a023ca9f793b058d9f4"
    TreasuryObjectInitialSharedVersion = 586569722
    PrivateKeyFile = "keys/sui.sk" # the path to the file containing the relayer eth private key
    IntervalToWaitForTransferInSeconds = 50 #50 seconds
    MaxRetriesOnQuorumReached = 3
    ClientAvailabilityAllowDelta = 10

[MultiversX]
    NetworkAddress = "https://devnet-gateway.multiversx.com" # the network address
    MultisigContractAddress = "erd1qqqqqqqqqqqqqpgq9ext3ys02vm534k4dkykp9y8sraza0uhpqqqvzw8pf" # the multiversx address for the bridge contract
    SafeContractAddress = "erd1qqqqqqqqqqqqqpgq70egmrllnh9r05kcxqtfaaj0dukewu2npqqqk0g46m" # the multiversx address for the safe contract
    PrivateKeyFile = "keys/multiversx.pem" # the path to the pem file containing the relayer multiversx wallet
    IntervalToResendTxsInSeconds = 60 # the time in seconds between nonce reads
    MaxRetriesOnQuorumReached = 3
    MaxRetriesOnWasTransferProposed = 3
    ClientAvailabilityAllowDelta = 10
    [MultiversX.Proxy]
        CacherExpirationSeconds = 600 # the caching time in seconds

        # valid options for ProxyRestAPIEntityType are "observer" and "proxy". Any other value will trigger an error.
        # "observer" is useful when querying an observer, directly and "proxy" is useful when querying a squad's proxy (gateway)
        RestAPIEntityType = "proxy"
        FinalityCheck = true
        MaxNoncesDelta = 7 # the number of maximum blocks allowed to be "in front" of what the metachain has notarized
    [MultiversX.GasMap]
        Sign = 8000000
        ProposeTransferBase = 11000000
        ProposeTransferForEach = 5500000
        ProposeStatusBase = 10000000
        ProposeStatusForEach = 7000000
        PerformActionBase = 40000000
        PerformActionForEach = 5500000
        ScCallPerByte = 100000 # 1500 tx data field + the rest for the actual storage in the contract
        ScCallPerformForEach = 10000000

[P2P]
    Port = "10011"
    InitialPeerList = ["/ip4/127.0.0.1/tcp/10000/p2p/16Uiu2HAmPejBkUKHWN9cGfxZAYNzkkXv5pphZhi1N4HXS5m61Uwk"]
    ProtocolID = "/devnet/sui/sui-testnet"
    [P2P.Transports]
        QUICAddress = "" # optional QUIC address. If this transport should be activated, should be in this format: /ip4/0.0.0.0/udp/%d/quic-v1
        WebSocketAddress = "" # optional WebSocket address. If this transport should be activated, should be in this format: /ip4/0.0.0.0/tcp/%d/ws
        WebTransportAddress = "" # optional WebTransport address. If this transport should be activated, should be in this format: /ip4/0.0.0.0/udp/%d/quic-v1/webtransport
        [P2P.Transports.TCP]
            ListenAddress = "/ip4/0.0.0.0/tcp/%d" # TCP listen address
            PreventPortReuse = false
        [P2P.ResourceLimiter]
            Type = "default autoscale" #available options "default autoscale", "infinite", "default with manual scale".
            ManualSystemMemoryInMB = 0 # not taken into account if the type is not "default with manual scale"
            ManualMaximumFD = 0 # not taken into account if the type is not "default with manual scale"
    [P2P.AntifloodConfig]
        Enabled = true
        NumConcurrentResolverJobs = 50
        [P2P.AntifloodConfig.FastReacting]
            IntervalInSeconds = 1
            ReservedPercent   = 20.0
            [P2P.AntifloodConfig.FastReacting.PeerMaxInput]
                BaseMessagesPerInterval  = 10
                TotalSizePerInterval = 1048576 #1MB/s
                [P2P.AntifloodConfig.FastReacting.PeerMaxInput.IncreaseFactor]
                    Threshold = 10 #if consensus size will exceed this value, then
                    Factor = 1.0   #increase the base value with [factor*consensus size]
            [P2P.AntifloodConfig.FastReacting.BlackList]
                ThresholdNumMessagesPerInterval = 70
                ThresholdSizePerInterval = 2097154 #2MB/s
                NumFloodingRounds = 10
                PeerBanDurationInSeconds = 300

        [P2P.AntifloodConfig.SlowReacting]
            IntervalInSeconds = 30
            ReservedPercent   = 20.0
            [P2P.AntifloodConfig.SlowReacting.PeerMaxInput]
                BaseMessagesPerInterval = 400
                TotalSizePerInterval = 10485760 #10MB/interval
                [P2P.AntifloodConfig.SlowReacting.PeerMaxInput.IncreaseFactor]
                    Threshold = 10 #if consensus size will exceed this value, then
                    Factor = 0.0   #increase the base value with [factor*consensus size]
            [P2P.AntifloodConfig.SlowReacting.BlackList]
                ThresholdNumMessagesPerInterval = 800
                ThresholdSizePerInterval = 20971540 #20MB/interval
                NumFloodingRounds = 2
                PeerBanDurationInSeconds = 3600

        [P2P.AntifloodConfig.OutOfSpecs]
            IntervalInSeconds = 1
            ReservedPercent   = 0.0
            [P2P.AntifloodConfig.OutOfSpecs.PeerMaxInput]
                BaseMessagesPerInterval = 140
                TotalSizePerInterval = 4194304 #4MB/s
                [P2P.AntifloodConfig.OutOfSpecs.PeerMaxInput.IncreaseFactor]
                    Threshold = 0 #if consensus size will exceed this value, then
                    Factor = 0.0     #increase the base value with [factor*consensus size]
            [P2P.AntifloodConfig.OutOfSpecs.BlackList]
                ThresholdNumMessagesPerInterval = 200
                ThresholdSizePerInterval = 6291456 #6MB/s
                NumFloodingRounds = 2
                PeerBanDurationInSeconds = 3600

        [P2P.AntifloodConfig.PeerMaxOutput]
            BaseMessagesPerInterval  = 5
            TotalSizePerInterval     = 524288 #512KB/s

        [P2P.AntifloodConfig.Cache]
            Name = "Antiflood"
            Capacity = 7000
            Type = "LRU"
        [P2P.AntifloodConfig.Topic]
            DefaultMaxMessagesPerSec = 300 # default number of messages per interval for a topic
            MaxMessages = [{ Topic = "SuiToMultiversX_join", NumMessagesPerSec = 100 },
                           { Topic = "SuiToMultiversX_sign", NumMessagesPerSec = 100 }]

[Relayer]
    [Relayer.Marshalizer]
        Type = "gogo protobuf"
        SizeCheckDelta = 10
    [Relayer.RoleProvider]
        PollingIntervalInMillis = 60000 # 1 minute
    [Relayer.StatusMetricsStorage]
        [Relayer.StatusMetricsStorage.Cache]
            Name = "StatusMetricsStorage"
            Capacity = 1000
            Type = "LRU"
        [Relayer.StatusMetricsStorage.DB]
            FilePath = "StatusMetricsStorageDB"
            Type = "LvlDBSerial"
            BatchDelaySeconds = 2
            MaxBatchSize = 100
            MaxOpenFiles = 10

[StateMachine]
    [StateMachine.SuiToMultiversX]
        StepDurationInMillis = 12000 #12 seconds
        IntervalForLeaderInSeconds = 120 #2 minutes

    [StateMachine.MultiversXToSui]
        StepDurationInMillis = 12000 #12 seconds
        IntervalForLeaderInSeconds = 120 #2 minutes

[Logs]
    LogFileLifeSpanInSec = 86400 # 24h
    LogFileLifeSpanInMB = 1024 # 1GB

[WebAntiflood]
    Enabled = true
    [WebAntiflood.WebServer]
            # SimultaneousRequests represents the number of concurrent requests accepted by the web server
            # this is a global throttler that acts on all http connections regardless of the originating source
            SimultaneousRequests = 100
            # SameSourceRequests defines how many requests are allowed from the same source in the specified
            # time frame (SameSourceResetIntervalInSec)
            SameSourceRequests = 10000
            # SameSourceResetIntervalInSec time frame between counter reset, in seconds
            SameSourceResetIntervalInSec = 1

[PeersRatingConfig]
    TopRatedCacheCapacity = 5000
    BadRatedCacheCapacity = 5000