version: "3.9"

services:
 chain-simulator:
  image: multiversx/chainsimulator:v1.8.4-fix1
  ports:
    - 8085:8085
  volumes:
    - "../scripts:/docker/scripts"
  entrypoint: "./chainsimulator -log-level *:INFO"
